# serverless.yml
service: user-notification-preferences-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    MONGODB_URI: ${ssm:/notification-api/mongodb-uri}
    
functions:
  app:
    handler: dist/serverless.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-nest
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

package:
  exclude:
    - node_modules/aws-sdk/**
    - node_modules/typescript/**
    - node_modules/@types/**
